name: 01-building-blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "hello world"

    echo-goodbye:
        runs-on: ubuntu-latest
        dep
        steps:
            - name: Successfull step
              run: |
                echo "i will Successed"
                exit 0
            - name: say goodbye
              run: echo "Goodbye"